FROM eclipse-temurin:17

WORKDIR /app

# ARG JAR_FILE=target/servicio-depositos-1.0-SNAPSHOT.jar

# COPY ${JAR_FILE} app.jar

COPY target/*.jar app.jar

EXPOSE 8083

ENTRYPOINT [ "java", "-jar", "app.jar" ]