// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace complejoDeportivo.Models;

public partial class Almacen
{
    public int AlmacenId { get; set; }

    public string Nombre { get; set; }

    public int ComplejoId { get; set; }

    public virtual Complejo Complejo { get; set; }

    public virtual ICollection<MovimientoStock> MovimientoStocks { get; set; } = new List<MovimientoStock>();

    public virtual ICollection<Stock> Stocks { get; set; } = new List<Stock>();
}