// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace complejoDeportivo.Models;

public partial class Asador
{
    public int AsadorId { get; set; }

    public int ComplejoId { get; set; }

    public string Nombre { get; set; }

    public decimal PrecioHora { get; set; }

    public bool Activo { get; set; }

    public virtual Complejo Complejo { get; set; }

    public virtual ICollection<DetalleReservaAsador> DetalleReservaAsadors { get; set; } = new List<DetalleReservaAsador>();
}