// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace complejoDeportivo.Models;

public partial class CalendarioFeriado
{
    public int FeriadoId { get; set; }

    public DateOnly Fecha { get; set; }

    public string Descripcion { get; set; }
}