// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using complejoDeportivo.DTOs;

namespace complejoDeportivo.Models;

public partial class Cancha
{
	public int CanchaId { get; set; }

	public int ComplejoId { get; set; }

	public int TipoCanchaId { get; set; }

	public int TipoSuperficieId { get; set; }

	public string Nombre { get; set; }

	public bool Activa { get; set; }

	public virtual ICollection<BloqueoCancha> BloqueoCanchas { get; set; } = new List<BloqueoCancha>();

	public virtual Complejo Complejo { get; set; }

	public virtual ICollection<DetalleReserva> DetalleReservas { get; set; } = new List<DetalleReserva>();

	public virtual ICollection<Tarifa> Tarifas { get; set; } = new List<Tarifa>();

	public virtual TipoCancha TipoCancha { get; set; }

	public virtual TipoSuperficie TipoSuperficie { get; set; }

	public Cancha(CrearCanchaDTO canchaDTO)
	{
		ComplejoId = canchaDTO.ComplejoId;
		TipoCanchaId = canchaDTO.TipoCanchaId;
		TipoSuperficieId = canchaDTO.TipoSuperficieId;
		Nombre = canchaDTO.Nombre;
		Activa = false;
	}
}