// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace complejoDeportivo.Models;

public partial class ComplejoDeportivoContext : DbContext
{
    public ComplejoDeportivoContext(DbContextOptions<ComplejoDeportivoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Almacen> Almacens { get; set; }

    public virtual DbSet<Asador> Asadors { get; set; }

    public virtual DbSet<BloqueoCancha> BloqueoCanchas { get; set; }

    public virtual DbSet<CalendarioFeriado> CalendarioFeriados { get; set; }

    public virtual DbSet<Cancha> Canchas { get; set; }

    public virtual DbSet<CategoriaProducto> CategoriaProductos { get; set; }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<Complejo> Complejos { get; set; }

    public virtual DbSet<DetalleReserva> DetalleReservas { get; set; }

    public virtual DbSet<DetalleReservaAsador> DetalleReservaAsadors { get; set; }

    public virtual DbSet<Direccion> Direccions { get; set; }

    public virtual DbSet<Empleado> Empleados { get; set; }

    public virtual DbSet<EstadoPago> EstadoPagos { get; set; }

    public virtual DbSet<EstadoReserva> EstadoReservas { get; set; }

    public virtual DbSet<Factura> Facturas { get; set; }

    public virtual DbSet<FacturaDetalle> FacturaDetalles { get; set; }

    public virtual DbSet<FormaPago> FormaPagos { get; set; }

    public virtual DbSet<MovimientoStock> MovimientoStocks { get; set; }

    public virtual DbSet<Pago> Pagos { get; set; }

    public virtual DbSet<PedidoKiosko> PedidoKioskos { get; set; }

    public virtual DbSet<PedidoKioskoDetalle> PedidoKioskoDetalles { get; set; }

    public virtual DbSet<Producto> Productos { get; set; }

    public virtual DbSet<ProductoProveedor> ProductoProveedors { get; set; }

    public virtual DbSet<Proveedor> Proveedors { get; set; }

    public virtual DbSet<ProveedorContacto> ProveedorContactos { get; set; }

    public virtual DbSet<Reserva> Reservas { get; set; }

    public virtual DbSet<ReservaAsador> ReservaAsadors { get; set; }

    public virtual DbSet<Stock> Stocks { get; set; }

    public virtual DbSet<Tarifa> Tarifas { get; set; }

    public virtual DbSet<TipoCancha> TipoCanchas { get; set; }

    public virtual DbSet<TipoComprobante> TipoComprobantes { get; set; }

    public virtual DbSet<TipoMovimientoStock> TipoMovimientoStocks { get; set; }

    public virtual DbSet<TipoSuperficie> TipoSuperficies { get; set; }

    public virtual DbSet<UnidadMedidum> UnidadMedida { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Almacen>(entity =>
        {
            entity.HasKey(e => e.AlmacenId).HasName("PK__Almacen__022A0856873D4667");

            entity.ToTable("Almacen");

            entity.Property(e => e.AlmacenId).HasColumnName("AlmacenID");
            entity.Property(e => e.ComplejoId).HasColumnName("ComplejoID");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Complejo).WithMany(p => p.Almacens)
                .HasForeignKey(d => d.ComplejoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Almacen__Complej__1332DBDC");
        });

        modelBuilder.Entity<Asador>(entity =>
        {
            entity.HasKey(e => e.AsadorId).HasName("PK__Asador__28240E5E3266731D");

            entity.ToTable("Asador");

            entity.Property(e => e.AsadorId).HasColumnName("AsadorID");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.ComplejoId).HasColumnName("ComplejoID");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PrecioHora).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Complejo).WithMany(p => p.Asadors)
                .HasForeignKey(d => d.ComplejoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Asador__Complejo__6A30C649");
        });

        modelBuilder.Entity<BloqueoCancha>(entity =>
        {
            entity.HasKey(e => e.BloqueoId).HasName("PK__BloqueoC__4F0C43DD4F3E0362");

            entity.ToTable("BloqueoCancha");

            entity.Property(e => e.BloqueoId).HasColumnName("BloqueoID");
            entity.Property(e => e.CanchaId).HasColumnName("CanchaID");
            entity.Property(e => e.Motivo)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Cancha).WithMany(p => p.BloqueoCanchas)
                .HasForeignKey(d => d.CanchaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BloqueoCa__Canch__5812160E");
        });

        modelBuilder.Entity<CalendarioFeriado>(entity =>
        {
            entity.HasKey(e => e.FeriadoId).HasName("PK__Calendar__DBAC383C06662A22");

            entity.Property(e => e.FeriadoId).HasColumnName("FeriadoID");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(150);
        });

        modelBuilder.Entity<Cancha>(entity =>
        {
            entity.HasKey(e => e.CanchaId).HasName("PK__Cancha__A3D3182899AD89E2");

            entity.ToTable("Cancha");

            entity.Property(e => e.CanchaId).HasColumnName("CanchaID");
            entity.Property(e => e.Activa).HasDefaultValue(true);
            entity.Property(e => e.ComplejoId).HasColumnName("ComplejoID");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TipoCanchaId).HasColumnName("TipoCanchaID");
            entity.Property(e => e.TipoSuperficieId).HasColumnName("TipoSuperficieID");

            entity.HasOne(d => d.Complejo).WithMany(p => p.Canchas)
                .HasForeignKey(d => d.ComplejoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Cancha__Complejo__5165187F");

            entity.HasOne(d => d.TipoCancha).WithMany(p => p.Canchas)
                .HasForeignKey(d => d.TipoCanchaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Cancha__TipoCanc__52593CB8");

            entity.HasOne(d => d.TipoSuperficie).WithMany(p => p.Canchas)
                .HasForeignKey(d => d.TipoSuperficieId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Cancha__TipoSupe__534D60F1");
        });

        modelBuilder.Entity<CategoriaProducto>(entity =>
        {
            entity.HasKey(e => e.CategoriaId).HasName("PK__Categori__F353C1C5630A7D37");

            entity.ToTable("CategoriaProducto");

            entity.Property(e => e.CategoriaId).HasColumnName("CategoriaID");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.ClienteId).HasName("PK__Cliente__71ABD0A7397231DF");

            entity.ToTable("Cliente");

            entity.Property(e => e.ClienteId).HasColumnName("ClienteID");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Documento).HasMaxLength(20);
            entity.Property(e => e.Email).HasMaxLength(150);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Telefono).HasMaxLength(20);
        });

        modelBuilder.Entity<Complejo>(entity =>
        {
            entity.HasKey(e => e.ComplejoId).HasName("PK__Complejo__FF080486987B676E");

            entity.ToTable("Complejo");

            entity.Property(e => e.ComplejoId).HasColumnName("ComplejoID");
            entity.Property(e => e.DireccionId).HasColumnName("DireccionID");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Direccion).WithMany(p => p.Complejos)
                .HasForeignKey(d => d.DireccionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Complejo__Direcc__4D94879B");
        });

        modelBuilder.Entity<DetalleReserva>(entity =>
        {
            entity.HasKey(e => e.DetalleReservaId).HasName("PK__DetalleR__9B4CBCC046006B63");

            entity.ToTable("DetalleReserva");

            entity.Property(e => e.DetalleReservaId).HasColumnName("DetalleReservaID");
            entity.Property(e => e.CanchaId).HasColumnName("CanchaID");
            entity.Property(e => e.Descuento).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Recargo).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ReservaId).HasColumnName("ReservaID");
            entity.Property(e => e.Subtotal).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.TarifaHoraId).HasColumnName("TarifaHoraID");

            entity.HasOne(d => d.Cancha).WithMany(p => p.DetalleReservas)
                .HasForeignKey(d => d.CanchaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DetalleRe__Canch__656C112C");

            entity.HasOne(d => d.Reserva).WithMany(p => p.DetalleReservas)
                .HasForeignKey(d => d.ReservaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DetalleRe__Reser__6477ECF3");

            entity.HasOne(d => d.TarifaHora).WithMany(p => p.DetalleReservas)
                .HasForeignKey(d => d.TarifaHoraId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DetalleRe__Tarif__66603565");
        });

        modelBuilder.Entity<DetalleReservaAsador>(entity =>
        {
            entity.HasKey(e => e.DetalleRaid).HasName("PK__DetalleR__05B66D72C72CA2B6");

            entity.ToTable("DetalleReservaAsador");

            entity.Property(e => e.DetalleRaid).HasColumnName("DetalleRAID");
            entity.Property(e => e.AsadorId).HasColumnName("AsadorID");
            entity.Property(e => e.PrecioHora).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ReservaAsadorId).HasColumnName("ReservaAsadorID");
            entity.Property(e => e.Subtotal).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Asador).WithMany(p => p.DetalleReservaAsadors)
                .HasForeignKey(d => d.AsadorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DetalleRe__Asado__71D1E811");

            entity.HasOne(d => d.ReservaAsador).WithMany(p => p.DetalleReservaAsadors)
                .HasForeignKey(d => d.ReservaAsadorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DetalleRe__Reser__70DDC3D8");
        });

        modelBuilder.Entity<Direccion>(entity =>
        {
            entity.HasKey(e => e.DireccionId).HasName("PK__Direccio__68906D44C4F5FE3F");

            entity.ToTable("Direccion");

            entity.Property(e => e.DireccionId).HasColumnName("DireccionID");
            entity.Property(e => e.Calle)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Ciudad)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CodigoPostal)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.Numero)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.Provincia)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Empleado>(entity =>
        {
            entity.HasKey(e => e.EmpleadoId).HasName("PK__Empleado__958BE6F029ED00AD");

            entity.ToTable("Empleado");

            entity.Property(e => e.EmpleadoId).HasColumnName("EmpleadoID");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Cargo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Email).HasMaxLength(150);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Telefono).HasMaxLength(20);
        });

        modelBuilder.Entity<EstadoPago>(entity =>
        {
            entity.HasKey(e => e.EstadoPagoId).HasName("PK__EstadoPa__63AD30BDC1E8792D");

            entity.ToTable("EstadoPago");

            entity.Property(e => e.EstadoPagoId).HasColumnName("EstadoPagoID");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<EstadoReserva>(entity =>
        {
            entity.HasKey(e => e.EstadoReservaId).HasName("PK__EstadoRe__DB6E9F018CE64B70");

            entity.ToTable("EstadoReserva");

            entity.Property(e => e.EstadoReservaId).HasColumnName("EstadoReservaID");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Factura>(entity =>
        {
            entity.HasKey(e => e.FacturaId).HasName("PK__Factura__5C0248057B6F87E5");

            entity.ToTable("Factura");

            entity.HasIndex(e => e.Fecha, "idx_factura_fecha");

            entity.Property(e => e.FacturaId).HasColumnName("FacturaID");
            entity.Property(e => e.ClienteId).HasColumnName("ClienteID");
            entity.Property(e => e.FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.NumeroComprobante)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.TipoComprobanteId).HasColumnName("TipoComprobanteID");
            entity.Property(e => e.Total).HasColumnType("decimal(12, 2)");

            entity.HasOne(d => d.Cliente).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.ClienteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Factura__Cliente__2739D489");

            entity.HasOne(d => d.TipoComprobante).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.TipoComprobanteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Factura__TipoCom__282DF8C2");
        });

        modelBuilder.Entity<FacturaDetalle>(entity =>
        {
            entity.HasKey(e => e.FacturaDetalleId).HasName("PK__FacturaD__A9674B1A70BCAE22");

            entity.ToTable("FacturaDetalle");

            entity.Property(e => e.FacturaDetalleId).HasColumnName("FacturaDetalleID");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.FacturaId).HasColumnName("FacturaID");
            entity.Property(e => e.PedidoId).HasColumnName("PedidoID");
            entity.Property(e => e.ReservaAsadorId).HasColumnName("ReservaAsadorID");
            entity.Property(e => e.ReservaId).HasColumnName("ReservaID");
            entity.Property(e => e.Subtotal).HasColumnType("decimal(12, 2)");

            entity.HasOne(d => d.Factura).WithMany(p => p.FacturaDetalles)
                .HasForeignKey(d => d.FacturaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__FacturaDe__Factu__2B0A656D");

            entity.HasOne(d => d.Pedido).WithMany(p => p.FacturaDetalles)
                .HasForeignKey(d => d.PedidoId)
                .HasConstraintName("FK__FacturaDe__Pedid__2CF2ADDF");

            entity.HasOne(d => d.ReservaAsador).WithMany(p => p.FacturaDetalles)
                .HasForeignKey(d => d.ReservaAsadorId)
                .HasConstraintName("FK__FacturaDe__Reser__2DE6D218");

            entity.HasOne(d => d.Reserva).WithMany(p => p.FacturaDetalles)
                .HasForeignKey(d => d.ReservaId)
                .HasConstraintName("FK__FacturaDe__Reser__2BFE89A6");
        });

        modelBuilder.Entity<FormaPago>(entity =>
        {
            entity.HasKey(e => e.FormaPagoId).HasName("PK__FormaPag__920B091EAEA81EF9");

            entity.ToTable("FormaPago");

            entity.Property(e => e.FormaPagoId).HasColumnName("FormaPagoID");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<MovimientoStock>(entity =>
        {
            entity.HasKey(e => e.MovimientoId).HasName("PK__Movimien__BF923FCC7D0D7E8A");

            entity.ToTable("MovimientoStock");

            entity.HasIndex(e => e.Fecha, "idx_movimientostock_fecha");

            entity.Property(e => e.MovimientoId).HasColumnName("MovimientoID");
            entity.Property(e => e.AlmacenId).HasColumnName("AlmacenID");
            entity.Property(e => e.Fecha).HasColumnType("datetime");
            entity.Property(e => e.Observaciones).HasMaxLength(200);
            entity.Property(e => e.ProductoId).HasColumnName("ProductoID");
            entity.Property(e => e.TipoMovimientoId).HasColumnName("TipoMovimientoID");

            entity.HasOne(d => d.Almacen).WithMany(p => p.MovimientoStocks)
                .HasForeignKey(d => d.AlmacenId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Movimient__Almac__1CBC4616");

            entity.HasOne(d => d.Producto).WithMany(p => p.MovimientoStocks)
                .HasForeignKey(d => d.ProductoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Movimient__Produ__1BC821DD");

            entity.HasOne(d => d.TipoMovimiento).WithMany(p => p.MovimientoStocks)
                .HasForeignKey(d => d.TipoMovimientoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Movimient__TipoM__1DB06A4F");
        });

        modelBuilder.Entity<Pago>(entity =>
        {
            entity.HasKey(e => e.PagoId).HasName("PK__Pago__F00B6158044BF1DD");

            entity.ToTable("Pago");

            entity.Property(e => e.PagoId).HasColumnName("PagoID");
            entity.Property(e => e.EstadoPagoId).HasColumnName("EstadoPagoID");
            entity.Property(e => e.FacturaId).HasColumnName("FacturaID");
            entity.Property(e => e.FechaPago).HasColumnType("datetime");
            entity.Property(e => e.FormaPagoId).HasColumnName("FormaPagoID");
            entity.Property(e => e.Monto).HasColumnType("decimal(12, 2)");

            entity.HasOne(d => d.EstadoPago).WithMany(p => p.Pagos)
                .HasForeignKey(d => d.EstadoPagoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pago__EstadoPago__32AB8735");

            entity.HasOne(d => d.Factura).WithMany(p => p.Pagos)
                .HasForeignKey(d => d.FacturaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pago__FacturaID__30C33EC3");

            entity.HasOne(d => d.FormaPago).WithMany(p => p.Pagos)
                .HasForeignKey(d => d.FormaPagoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pago__FormaPagoI__31B762FC");
        });

        modelBuilder.Entity<PedidoKiosko>(entity =>
        {
            entity.HasKey(e => e.PedidoId).HasName("PK__PedidoKi__09BA14103D805AE8");

            entity.ToTable("PedidoKiosko");

            entity.HasIndex(e => e.Fecha, "idx_pedido_fecha");

            entity.Property(e => e.PedidoId).HasColumnName("PedidoID");
            entity.Property(e => e.ClienteId).HasColumnName("ClienteID");
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Fecha).HasColumnType("datetime");
            entity.Property(e => e.Total).HasColumnType("decimal(12, 2)");

            entity.HasOne(d => d.Cliente).WithMany(p => p.PedidoKioskos)
                .HasForeignKey(d => d.ClienteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PedidoKio__Clien__208CD6FA");
        });

        modelBuilder.Entity<PedidoKioskoDetalle>(entity =>
        {
            entity.HasKey(e => e.DetalleId).HasName("PK__PedidoKi__6E19D6FADA1C8592");

            entity.ToTable("PedidoKioskoDetalle");

            entity.Property(e => e.DetalleId).HasColumnName("DetalleID");
            entity.Property(e => e.PedidoId).HasColumnName("PedidoID");
            entity.Property(e => e.PrecioUnitario).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ProductoId).HasColumnName("ProductoID");
            entity.Property(e => e.Subtotal).HasColumnType("decimal(12, 2)");

            entity.HasOne(d => d.Pedido).WithMany(p => p.PedidoKioskoDetalles)
                .HasForeignKey(d => d.PedidoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PedidoKio__Pedid__236943A5");

            entity.HasOne(d => d.Producto).WithMany(p => p.PedidoKioskoDetalles)
                .HasForeignKey(d => d.ProductoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PedidoKio__Produ__245D67DE");
        });

        modelBuilder.Entity<Producto>(entity =>
        {
            entity.HasKey(e => e.ProductoId).HasName("PK__Producto__A430AE8364B2C534");

            entity.ToTable("Producto");

            entity.HasIndex(e => e.ProductoId, "idx_precioproducto_vigencia");

            entity.Property(e => e.ProductoId).HasColumnName("ProductoID");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.CategoriaId).HasColumnName("CategoriaID");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PrecioBase).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.UnidadId).HasColumnName("UnidadID");

            entity.HasOne(d => d.Categoria).WithMany(p => p.Productos)
                .HasForeignKey(d => d.CategoriaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Producto__Catego__0A9D95DB");

            entity.HasOne(d => d.Unidad).WithMany(p => p.Productos)
                .HasForeignKey(d => d.UnidadId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Producto__Unidad__0B91BA14");
        });

        modelBuilder.Entity<ProductoProveedor>(entity =>
        {
            entity.HasKey(e => e.ProdProvId).HasName("PK__Producto__7227C12DEFB2FF45");

            entity.ToTable("ProductoProveedor");

            entity.Property(e => e.ProdProvId).HasColumnName("ProdProvID");
            entity.Property(e => e.PrecioCompra).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ProductoId).HasColumnName("ProductoID");
            entity.Property(e => e.ProveedorId).HasColumnName("ProveedorID");

            entity.HasOne(d => d.Producto).WithMany(p => p.ProductoProveedors)
                .HasForeignKey(d => d.ProductoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductoP__Produ__0F624AF8");

            entity.HasOne(d => d.Proveedor).WithMany(p => p.ProductoProveedors)
                .HasForeignKey(d => d.ProveedorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductoP__Prove__10566F31");
        });

        modelBuilder.Entity<Proveedor>(entity =>
        {
            entity.HasKey(e => e.ProveedorId).HasName("PK__Proveedo__61266BB9A68336A8");

            entity.ToTable("Proveedor");

            entity.Property(e => e.ProveedorId).HasColumnName("ProveedorID");
            entity.Property(e => e.Cuit)
                .HasMaxLength(20)
                .HasColumnName("CUIT");
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Telefono).HasMaxLength(50);
        });

        modelBuilder.Entity<ProveedorContacto>(entity =>
        {
            entity.HasKey(e => e.ContactoId).HasName("PK__Proveedo__8E0F85C833714677");

            entity.ToTable("ProveedorContacto");

            entity.Property(e => e.ContactoId).HasColumnName("ContactoID");
            entity.Property(e => e.Cargo).HasMaxLength(50);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ProveedorId).HasColumnName("ProveedorID");
            entity.Property(e => e.Telefono).HasMaxLength(50);

            entity.HasOne(d => d.Proveedor).WithMany(p => p.ProveedorContactos)
                .HasForeignKey(d => d.ProveedorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Proveedor__Prove__76969D2E");
        });

        modelBuilder.Entity<Reserva>(entity =>
        {
            entity.HasKey(e => e.ReservaId).HasName("PK__Reserva__C399370356E70E8D");

            entity.ToTable("Reserva");

            entity.HasIndex(e => e.ClienteId, "idx_reserva_cliente");

            entity.HasIndex(e => e.Fecha, "idx_reserva_fecha");

            entity.Property(e => e.ReservaId).HasColumnName("ReservaID");
            entity.Property(e => e.Ambito)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.ClienteId).HasColumnName("ClienteID");
            entity.Property(e => e.EstadoReservaId).HasColumnName("EstadoReservaID");
            entity.Property(e => e.FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Total).HasColumnType("decimal(12, 2)");

            entity.HasOne(d => d.Cliente).WithMany(p => p.Reservas)
                .HasForeignKey(d => d.ClienteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Reserva__Cliente__5AEE82B9");

            entity.HasOne(d => d.EstadoReserva).WithMany(p => p.Reservas)
                .HasForeignKey(d => d.EstadoReservaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Reserva__EstadoR__5BE2A6F2");
        });

        modelBuilder.Entity<ReservaAsador>(entity =>
        {
            entity.HasKey(e => e.ReservaAsadorId).HasName("PK__ReservaA__5063B12B9AF53F70");

            entity.ToTable("ReservaAsador");

            entity.HasIndex(e => e.Fecha, "idx_reservaasador_fecha");

            entity.Property(e => e.ReservaAsadorId).HasColumnName("ReservaAsadorID");
            entity.Property(e => e.ClienteId).HasColumnName("ClienteID");
            entity.Property(e => e.EstadoReservaId).HasColumnName("EstadoReservaID");
            entity.Property(e => e.FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Total).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Cliente).WithMany(p => p.ReservaAsadors)
                .HasForeignKey(d => d.ClienteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ReservaAs__Clien__6D0D32F4");

            entity.HasOne(d => d.EstadoReserva).WithMany(p => p.ReservaAsadors)
                .HasForeignKey(d => d.EstadoReservaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ReservaAs__Estad__6E01572D");
        });

        modelBuilder.Entity<Stock>(entity =>
        {
            entity.HasKey(e => e.StockId).HasName("PK__Stock__2C83A9E285FAF84B");

            entity.ToTable("Stock");

            entity.HasIndex(e => e.ProductoId, "idx_stock_producto");

            entity.Property(e => e.StockId).HasColumnName("StockID");
            entity.Property(e => e.AlmacenId).HasColumnName("AlmacenID");
            entity.Property(e => e.ProductoId).HasColumnName("ProductoID");

            entity.HasOne(d => d.Almacen).WithMany(p => p.Stocks)
                .HasForeignKey(d => d.AlmacenId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Stock__AlmacenID__18EBB532");

            entity.HasOne(d => d.Producto).WithMany(p => p.Stocks)
                .HasForeignKey(d => d.ProductoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Stock__ProductoI__17F790F9");
        });

        modelBuilder.Entity<Tarifa>(entity =>
        {
            entity.HasKey(e => e.TarifaId).HasName("PK__Tarifa__E81AC21B359437A3");

            entity.ToTable("Tarifa");

            entity.HasIndex(e => e.FechaVigencia, "idx_tarifa_vigencia");

            entity.Property(e => e.TarifaId).HasColumnName("TarifaID");
            entity.Property(e => e.CanchaId).HasColumnName("CanchaID");
            entity.Property(e => e.EsActual).HasDefaultValue(true);
            entity.Property(e => e.Precio).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Cancha).WithMany(p => p.Tarifas)
                .HasForeignKey(d => d.CanchaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Tarifa__CanchaID__5FB337D6");
        });

        modelBuilder.Entity<TipoCancha>(entity =>
        {
            entity.HasKey(e => e.TipoCanchaId).HasName("PK__TipoCanc__C40B8FACC57D4CC3");

            entity.ToTable("TipoCancha");

            entity.Property(e => e.TipoCanchaId).HasColumnName("TipoCanchaID");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TipoComprobante>(entity =>
        {
            entity.HasKey(e => e.TipoComprobanteId).HasName("PK__TipoComp__2055499645907F64");

            entity.ToTable("TipoComprobante");

            entity.Property(e => e.TipoComprobanteId).HasColumnName("TipoComprobanteID");
            entity.Property(e => e.CodigoAfip)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("CodigoAFIP");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TipoMovimientoStock>(entity =>
        {
            entity.HasKey(e => e.TipoMovimientoId).HasName("PK__TipoMovi__097C73016AC7B73D");

            entity.ToTable("TipoMovimientoStock");

            entity.Property(e => e.TipoMovimientoId).HasColumnName("TipoMovimientoID");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TipoSuperficie>(entity =>
        {
            entity.HasKey(e => e.TipoSuperficieId).HasName("PK__TipoSupe__F87A58D1C7BE5EBB");

            entity.ToTable("TipoSuperficie");

            entity.Property(e => e.TipoSuperficieId).HasColumnName("TipoSuperficieID");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<UnidadMedidum>(entity =>
        {
            entity.HasKey(e => e.UnidadId).HasName("PK__UnidadMe__C6F32436892F9F1C");

            entity.Property(e => e.UnidadId).HasColumnName("UnidadID");
            entity.Property(e => e.Abreviatura)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.UsuarioId).HasName("PK__Usuario__2B3DE7989D2F5358");

            entity.ToTable("Usuario");

            entity.HasIndex(e => e.Email, "UQ__Usuario__A9D10534790756C0").IsUnique();

            entity.HasIndex(e => e.ClienteId, "idx_usuario_cliente").HasFilter("([ClienteID] IS NOT NULL)");

            entity.HasIndex(e => e.Email, "idx_usuario_email").IsUnique();

            entity.HasIndex(e => e.EmpleadoId, "idx_usuario_empleado").HasFilter("([EmpleadoID] IS NOT NULL)");

            entity.Property(e => e.UsuarioId).HasColumnName("UsuarioID");
            entity.Property(e => e.ClienteId).HasColumnName("ClienteID");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.EmpleadoId).HasColumnName("EmpleadoID");
            entity.Property(e => e.FechaRegistro)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.TipoUsuario)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Cliente).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.ClienteId)
                .HasConstraintName("FK__Usuario__Cliente__3A4CA8FD");

            entity.HasOne(d => d.Empleado).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.EmpleadoId)
                .HasConstraintName("FK__Usuario__Emplead__3B40CD36");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}