// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace complejoDeportivo.Models;

public partial class DetalleReservaAsador
{
    public int DetalleRaid { get; set; }

    public int ReservaAsadorId { get; set; }

    public int AsadorId { get; set; }

    public decimal PrecioHora { get; set; }

    public int CantidadHoras { get; set; }

    public decimal Subtotal { get; set; }

    public virtual Asador Asador { get; set; }

    public virtual ReservaAsador ReservaAsador { get; set; }
}