// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace complejoDeportivo.Models;

public partial class DetalleReserva
{
    public int DetalleReservaId { get; set; }

    public int ReservaId { get; set; }

    public int CanchaId { get; set; }

    public int TarifaHoraId { get; set; }

    public int CantidadHoras { get; set; }

    public decimal Descuento { get; set; }

    public decimal Recargo { get; set; }

    public decimal Subtotal { get; set; }

    public virtual Cancha Cancha { get; set; }

    public virtual Reserva Reserva { get; set; }

    public virtual Tarifa TarifaHora { get; set; }
}