// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace complejoDeportivo.Models;

public partial class Direccion
{
    public int DireccionId { get; set; }

    public string Calle { get; set; }

    public string Numero { get; set; }

    public string Ciudad { get; set; }

    public string Provincia { get; set; }

    public string CodigoPostal { get; set; }

    public virtual ICollection<Complejo> Complejos { get; set; } = new List<Complejo>();
}