// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace complejoDeportivo.Models;

public partial class EstadoReserva
{
    public int EstadoReservaId { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<ReservaAsador> ReservaAsadors { get; set; } = new List<ReservaAsador>();

    public virtual ICollection<Reserva> Reservas { get; set; } = new List<Reserva>();
}