// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace complejoDeportivo.Models;

public partial class Factura
{
    public int FacturaId { get; set; }

    public int ClienteId { get; set; }

    public int TipoComprobanteId { get; set; }

    public DateOnly Fecha { get; set; }

    public string NumeroComprobante { get; set; }

    public decimal Total { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual Cliente Cliente { get; set; }

    public virtual ICollection<FacturaDetalle> FacturaDetalles { get; set; } = new List<FacturaDetalle>();

    public virtual ICollection<Pago> Pagos { get; set; } = new List<Pago>();

    public virtual TipoComprobante TipoComprobante { get; set; }
}