// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace complejoDeportivo.Models;

public partial class FacturaDetalle
{
    public int FacturaDetalleId { get; set; }

    public int FacturaId { get; set; }

    public int? ReservaId { get; set; }

    public int? PedidoId { get; set; }

    public int? ReservaAsadorId { get; set; }

    public string Descripcion { get; set; }

    public decimal Subtotal { get; set; }

    public virtual Factura Factura { get; set; }

    public virtual PedidoKiosko Pedido { get; set; }

    public virtual Reserva Reserva { get; set; }

    public virtual ReservaAsador ReservaAsador { get; set; }
}