// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace complejoDeportivo.Models;

public partial class MovimientoStock
{
    public int MovimientoId { get; set; }

    public int ProductoId { get; set; }

    public int AlmacenId { get; set; }

    public int Cantidad { get; set; }

    public DateTime Fecha { get; set; }

    public int TipoMovimientoId { get; set; }

    public string Observaciones { get; set; }

    public virtual Almacen Almacen { get; set; }

    public virtual Producto Producto { get; set; }

    public virtual TipoMovimientoStock TipoMovimiento { get; set; }
}