// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace complejoDeportivo.Models;

public partial class Pago
{
    public int PagoId { get; set; }

    public int FacturaId { get; set; }

    public int FormaPagoId { get; set; }

    public int EstadoPagoId { get; set; }

    public decimal Monto { get; set; }

    public DateTime FechaPago { get; set; }

    public virtual EstadoPago EstadoPago { get; set; }

    public virtual Factura Factura { get; set; }

    public virtual FormaPago FormaPago { get; set; }
}