// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace complejoDeportivo.Models;

public partial class Producto
{
    public int ProductoId { get; set; }

    public string Nombre { get; set; }

    public int CategoriaId { get; set; }

    public int UnidadId { get; set; }

    public decimal PrecioBase { get; set; }

    public bool Activo { get; set; }

    public virtual CategoriaProducto Categoria { get; set; }

    public virtual ICollection<MovimientoStock> MovimientoStocks { get; set; } = new List<MovimientoStock>();

    public virtual ICollection<PedidoKioskoDetalle> PedidoKioskoDetalles { get; set; } = new List<PedidoKioskoDetalle>();

    public virtual ICollection<ProductoProveedor> ProductoProveedors { get; set; } = new List<ProductoProveedor>();

    public virtual ICollection<Stock> Stocks { get; set; } = new List<Stock>();

    public virtual UnidadMedidum Unidad { get; set; }
}