// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace complejoDeportivo.Models;

public partial class ProductoProveedor
{
    public int ProdProvId { get; set; }

    public int ProductoId { get; set; }

    public int ProveedorId { get; set; }

    public decimal PrecioCompra { get; set; }

    public bool EsPrincipal { get; set; }

    public virtual Producto Producto { get; set; }

    public virtual Proveedor Proveedor { get; set; }
}