// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace complejoDeportivo.Models;

public partial class ReservaAsador
{
    public int ReservaAsadorId { get; set; }

    public int ClienteId { get; set; }

    public DateOnly Fecha { get; set; }

    public TimeOnly HoraInicio { get; set; }

    public TimeOnly HoraFin { get; set; }

    public int EstadoReservaId { get; set; }

    public decimal Total { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual Cliente Cliente { get; set; }

    public virtual ICollection<DetalleReservaAsador> DetalleReservaAsadors { get; set; } = new List<DetalleReservaAsador>();

    public virtual EstadoReserva EstadoReserva { get; set; }

    public virtual ICollection<FacturaDetalle> FacturaDetalles { get; set; } = new List<FacturaDetalle>();
}