// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace complejoDeportivo.Models;

public partial class Stock
{
    public int StockId { get; set; }

    public int ProductoId { get; set; }

    public int AlmacenId { get; set; }

    public int Cantidad { get; set; }

    public int StockMinimo { get; set; }

    public int StockMaximo { get; set; }

    public virtual Almacen Almacen { get; set; }

    public virtual Producto Producto { get; set; }
}