// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace complejoDeportivo.Models;

public partial class Tarifa
{
    public int TarifaId { get; set; }

    public int CanchaId { get; set; }

    public decimal Precio { get; set; }

    public bool ContratoLuz { get; set; }

    public DateOnly FechaVigencia { get; set; }

    public bool EsActual { get; set; }

    public virtual Cancha Cancha { get; set; }

    public virtual ICollection<DetalleReserva> DetalleReservas { get; set; } = new List<DetalleReserva>();
}