// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace complejoDeportivo.Models;

public partial class TipoComprobante
{
    public int TipoComprobanteId { get; set; }

    public string Nombre { get; set; }

    public string CodigoAfip { get; set; }

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();
}