// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace complejoDeportivo.Models;

public partial class TipoMovimientoStock
{
    public int TipoMovimientoId { get; set; }

    public string Nombre { get; set; }

    public bool AfectaStock { get; set; }

    public virtual ICollection<MovimientoStock> MovimientoStocks { get; set; } = new List<MovimientoStock>();
}