// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace complejoDeportivo.Models;

public partial class Usuario
{
    public int UsuarioId { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string TipoUsuario { get; set; }

    public int? ClienteId { get; set; }

    public int? EmpleadoId { get; set; }

    public DateTime FechaRegistro { get; set; }

    public virtual Cliente Cliente { get; set; }

    public virtual Empleado Empleado { get; set; }
}